-- Nominees or Denominees - migration relationnelle tournoi
--
-- Le modèle historique monolithique est remplacé par :
--   public.tiktokeurs  -> les profils TikTok évalués
--   public.dossiers    -> les preuves uploadées par les joueurs
--   public.ratings     -> les notes/commentaires croisés de chaque appareil
--
-- Pour éviter deux sources de vérité SQL, exécute le fichier complet :
--   supabase/schema.sql
--
-- Ce fichier reste présent uniquement pour documenter que l'ancienne migration
-- multijoueur/Spaces est dépréciée.
